dist: trusty
sudo: required
language: python
python:
  - 3.6
env:
  - R_LIBS_USER=$TRAVIS_BUILD_DIR
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y --allow-unauthenticated r-base
  -
install:
  - pip install pipenv
  - pipenv install
script:
  - python -m unittest discover tests
